/* Retorna se todas as tabelas do InvSCP existem */

(SELECT 1 FROM INFORMATION_SCHEMA.Tables WHERE TABLE_NAME='localizacao') 
INTERSECT
(SELECT 1 FROM INFORMATION_SCHEMA.Tables WHERE TABLE_NAME='predio')
INTERSECT
(SELECT 1 FROM INFORMATION_SCHEMA.Tables WHERE TABLE_NAME='departamento')
INTERSECT
(SELECT 1 FROM INFORMATION_SCHEMA.Tables WHERE TABLE_NAME='sala')
INTERSECT
(SELECT 1 FROM INFORMATION_SCHEMA.Tables WHERE TABLE_NAME='funcionario')
INTERSECT
(SELECT 1 FROM INFORMATION_SCHEMA.Tables WHERE TABLE_NAME='ordem_servico')
INTERSECT
(SELECT 1 FROM INFORMATION_SCHEMA.Tables WHERE TABLE_NAME='baixa')
INTERSECT
(SELECT 1 FROM INFORMATION_SCHEMA.Tables WHERE TABLE_NAME='grupo_material')
INTERSECT
(SELECT 1 FROM INFORMATION_SCHEMA.Tables WHERE TABLE_NAME='movimentacao')
INTERSECT
(SELECT 1 FROM INFORMATION_SCHEMA.Tables WHERE TABLE_NAME='evento_movimentacao')
